### ISSUE TITLE
add ability to merge secrets yaml file into template.yml for private servers

### ISSUE THREAD

**Issue by unixfox** [bolt-rip/nerve#10]
I would like to have a `template-secrets.yml` in `plugins/Nerve` that gets merged with `template.yml` for private servers.
This allows to not overriding the current template.yml and also allows me to load this `template-secrets.yml` from my helmfiles configuration.
The point of this is to have the secrets only loaded in the cluster.

template-secrets.yml example:
```yml
spec:
  values:
    luckperms:
      data:
        password: verysecretpassword
```
